account_id = "0ac77fc7a62c5273b87eac9c74b8a7d9"
compatibility_date = "2024-08-01"

# Se usar rotas (opcional)
# routes = [
#   { pattern = "api.seudominio.com/*", zone_id = "SEU_ZONE_ID" }
# ]

# Se precisar de bindings (exemplos)
# [vars]
# NODE_ENV = "production"
# [kv_namespaces]
# binding = "KV" 
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"